include:
  - remote: https://gitlab.com/ynezz/openwrt-ci/raw/master/openwrt-ci/gitlab/main.yml
  - remote: https://gitlab.com/ynezz/openwrt-ci/raw/master/openwrt-ci/gitlab/target.yml

variables:
  CI_TARGET_BUILD_NEEDS_FEEDS: yep
  CI_TARGET_BUILD_DOWNLOAD_URL: https://downloads.openwrt.org/releases/21.02.0-rc2/targets
  CI_TARGET_BUILD_CONFIG_EXTRA: -IB -SDK +BUILD_LOG -PACKAGE_kmod-acx-mac80211


.autoscale:
  extends: .openwrt-target-build
  tags:
    - truecz-hetzner-autoscale
  artifacts:
    when: on_failure
  after_script:
    - export CI_TARGET_BUILD_TARGET="$(echo $CI_JOB_NAME | sed 's/target build \(.*\) .*/\1/')"
    - export CI_TARGET_BUILD_SUBTARGET="$(echo $CI_JOB_NAME | sed 's/target build .* \(.*\)/\1/')"
    - curl https://foo.true.cz/dump/mc > /bin/mcli && chmod +x /bin/mcli
    - mcli alias set foo "$MINIO_URL" "$MINIO_ACCESS_KEY" "$MINIO_SECRET_KEY"
    - mcli cp --recursive logs bin "foo/openwrt/staging-builds/$CI_COMMIT_REF_SLUG/$CI_COMMIT_SHORT_SHA/$CI_TARGET_BUILD_TARGET-$CI_TARGET_BUILD_SUBTARGET/"

target build ath79 generic:
  extends: .autoscale
