---
blank_issues_enabled: true
contact_links:
  - name: Feature request
    url: https://forum.openwrt.org/c/feature-requests
    about: The OpenWrt project relies on volunteers. While we appreciate feature requests, we might lack the manpower to handle them. Ideally, you get familiar with the codebase and attempt to contribute the feature yourself. We recommend to post in the forum, as this is the most likely place to receive feedback on feature requests.
  - name: OpenWrt community
    url: https://openwrt.org/contact
    about: Consider reaching out to our community to get help. OpenWrt is a complex software project with many pitfalls; there is a good chance someone can help you solve your issue in no time.
  - name: OpenWrt documentation
    url: https://openwrt.org/docs/start
    about: The OpenWrt documentation contains a lot of valuable information.
