#
# 这是自由软件，许可证为MIT。
#
# 版权所有 (C) 2021 KFERMercer <KFER.Mercer@gmail.com>
#
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: Merge-upstream   # 工作流名称：合并上游

on:
  push:
    branches:
      - master         # 当 master 分支有 push 时触发
  schedule:
    - cron: 30 19 * * * # 每天UTC时间19:30自动触发（北京时间+8为03:30）

jobs:

  merge:

    runs-on: ubuntu-latest   # 运行环境

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master            # 检出 master 分支
        fetch-depth: 0         # 拉取所有提交历史（完整克隆，方便合并）
        lfs: true              # 支持 Git LFS 文件

    - name: Set git config
      run : |
        # 设置git用户信息（用于自动提交）
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git config --global pull.rebase false
        git config --global --list    # 显示全部 git 配置

    - name: Load upstream commits
      run: git pull https://github.com/coolsnowwolf/lede.git --log --no-commit
        # 拉取上游仓库（coolsnowwolf/lede）最新代码，但不自动commit

    - name: Apply commit changes
      run: |
        # 如果存在合并信息（说明有新内容要合并）
        if [ -f ./.git/MERGE_MSG ]; then
        mkdir ./tmp && cp ./.git/MERGE_MSG ./tmp/message
        sed -i "1c [bot] AutoMerging: merge all upstream's changes:" ./tmp/message
        # sed -i '/^\#.*/d' ./tmp/message    # 可选：去除注释行
        git commit --file="./tmp/message"   # 自动提交合并内容并使用自定义提交信息
        else
        echo "There is no merge commits."   # 否则输出无内容合并
        fi

    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: master
      run: git push origin $DOWNSTREAM_BRANCH   # 推送合并后的master分支到远程