name: Build OpenWrt

on:
  push:
    branches:
      - NewifiD2_Aria2_Ksmbd
  pull_request:
    branches:
      - NewifiD2_Aria2_Ksmbd
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk  \
          gcc-multilib g++-multilib g++-multilib gettext git libncurses-dev \
          libssl-dev python3 python3-setuptools rsync unzip zlib1g-dev file

      - name: Clone OpenWrt source
        run: |
          git clone --depth=1 https://github.com/openwrt/openwrt.git OpenWrt
          cd OpenWrt
          # cp ../.config ./

      - name: Install Feeds
        run: |
          cd OpenWrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build OpenWrt
        run: |
          cd OpenWrt
          # make defconfig
          make -j$(nproc) download
          make -j$(nproc) V=s

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt-Firmware
          path: OpenWrt/bin/
